//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryAppService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroceryIngredient
    {
        public int Id { get; set; }
        public int GroceryId { get; set; }
        public int IngredientId { get; set; }
        public Nullable<bool> Done { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual GroceryList GroceryList { get; set; }
        public virtual Ingredient Ingredient { get; set; }
    }
}
