//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryAppService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroceryRecipeList
    {
        public int Id { get; set; }
        public int GroceryId { get; set; }
        public int RecipeId { get; set; }
    
        public virtual GroceryList GroceryList { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
