export const SELECT_RECIPE = 'SELECT_RECIPE';
export const ADD_RECIPE_INGREDIENTS_TO_GROCERYLIST = 'ADD_RECIPE_INGREDIENTS_TO_GROCERYLIST';
export const GET_RECIPE_LIST = 'GET_RECIPE_LIST';
/* const REMOVE_TODO = 'REMOVE_TODO'
const LOAD_ARTICLE = 'LOAD_ARTICLE' */