export const SELECT_RECIPE = 'SELECT_RECIPE';
export const ADD_RECIPE_INGREDIENTS_TO_GROCERYLIST = 'ADD_RECIPE_INGREDIENTS_TO_GROCERYLIST';
export const GET_RECIPE_LIST = 'GET_RECIPE_LIST';
export const GET_REOCCURRING_GROCERY_LIST_ITEMS = 'GET_REOCCURRING_GROCERY_LIST_ITEMS';
export const ADD_REOCCURRING_ITEM_TO_GROCERYLIST = 'ADD_REOCCURRING_ITEM_TO_GROCERYLIST';
export const REQUEST_ADD_REOCCURRING_ITEM_TO_GROCERYLIST = 'REQUEST_ADD_REOCCURRING_ITEM_TO_GROCERYLIST';
/* const REMOVE_TODO = 'REMOVE_TODO'
const LOAD_ARTICLE = 'LOAD_ARTICLE' */